---
title: "Statistical Inference Notes"
author: "Howard J"
date: "December 10, 2017"
output:
html_document:
  highlight: pygments
  theme: spacelab
  toc: yes
header-includes: \usepackage{graphicx}
---

```{r message=FALSE, warning=FALSE}
library(UsingR)
library(tidyverse)
library(grid)
library(png)
```


## The Goals of Inference  
1. Estimate and quantify the *uncertainty of an estimate of a population quantity* (the proportion of people who will vote for a candidate).  
2. Determine whether a population quantity is a *benchmark value* (“is the treatment effective?”).  
3. Infer a *mechanistic relationship* when quantities are measured with noise (“What is the slope for Hooke’s law?”)  
4. Determine the impact of a policy? (“If we reduce pollution levels, will asthma rates decline?”)  
5. Talk about the probability that something occurs.  

## The tools of the trade  
1. Randomization: concerned with *balancing unobserved variables* that may confound inferences of interest.  
2. Random Sampling: concerned with obtaining data that is *representative of the population* of interest.  
3. Sampling Models: concerned with creating *a model for the sampling process*, the most common is so called “iid”.  
4. Hypothesis Testing: concerned with *decision making in the presence of uncertainty*.  
5. Confidence Intervals: concerned with *quantifying uncertainty* in estimation.  
6. Probability Models: a formal *connection between the data and a population* of interest. Often probability models are assumed or are approximated.  
7. Study Design: the process of designing an experiment *to minimize biases and variability*.  
8. Nonparametric Bootstrapping: the process of using the data to, *with minimal probability model assumptions, create inferences*.  
9. Permutation, Randomization and Exchangeability Testing: the process of *using data permutations to perform inferences*.  


## Different Styles of Inference
1. Frequency probability: is the long run proportion of times an event occurs in iid repetitions.  
2. Bayesian probability: is the probability calculus of beliefs, given that beliefs follow certain rules.  

1. Frequency style inference: *uses frequency interpretations of probabilities to control error rates*. Answers questions like “What should I decide given my data controlling the long run proportion of mistakes I make at a tolerable level.”  
2. Bayesian style inference: *uses Bayesian probability representation of beliefs to perform inference*. Answers questions like “Given my *subjective beliefs* and the *objective information* from the data, what should I believe now?”  

