---
title: "String Function Notes"
author: "Howard J"
date: "December 15, 2017"
output:
html_document:
  highlight: pygments
  theme: spacelab
  toc: yes
header-includes: \usepackage{graphicx}
---

```{r message=FALSE, warning=FALSE}
library(UsingR)
library(tidyverse)
library(grid)
library(png)
```

## Pattern Matching and Replacement    
`grep`, `grepl`, `regexpr`, `gregexpr` and `regexec` search for matches to argument pattern within each element of a character vector: they differ in the format of and amount of detail in the results.

sub and gsub perform replacement of the first and all matches respectively.



`sub(pattern, replacement, x)`  
`gsub(pattern, replacement, x)`  
Replace the *first occurrence* of a pattern with *sub*.  
Replace *all* occurrences with *gsub*.  
pattern – A pattern to search for, which is assumed to be a regular expression. Use an additional argument fixed=TRUE to look for a pattern without using regular expressions.
    replacement – A character string to replace the occurrence (or occurrences for gsub) of pattern.
    x – A character vector to search for pattern. Each element will be searched separately.


x <- c("This is a sentence about axis", "A second pattern is also listed here")
sub("is", "XY", x)
[1] "ThXY is a sentence about axis"       
[2] "A second pattern XY also listed here"
> gsub("is", "XY", x)
[1] "ThXY XY a sentence about axXY"       
[2] "A second pattern XY also lXYted here"
> 


## Sort or Ordering Vectors
Sort (or order) a vector or factor (partially) into ascending or descending order.


Usage

sort(x, decreasing = FALSE, ...)

## Default S3 method:
sort(x, decreasing = FALSE, na.last = NA, ...)

sort.int(x, partial = NULL, na.last = NA, decreasing = FALSE,
         method = c("auto", "shell", "quick", "radix"), index.return = FALSE)

x	
for sort an R object with a class or a numeric, complex, character or logical vector. For sort.int, a numeric, complex, character or logical vector, or a factor.
decreasing	
logical. Should the sort be increasing or decreasing? For the "radix" method, this can be a vector of length equal to the number of arguments in .... For the other methods, it must be length one. Not available for partial sorting.
...	
arguments to be passed to or from methods or (for the default methods and objects without a class) to sort.int.
na.last	
for controlling the treatment of NAs. If TRUE, missing values in the data are put last; if FALSE, they are put first; if NA, they are removed.
partial	
NULL or a vector of indices for partial sorting.
method	
character string specifying the algorithm used. Not available for partial sorting. Can be abbreviated.
index.return	
logical indicating if the ordering index vector should be returned as well. Supported by method == "radix" for any na.last mode and data type, and the other methods when na.last = NA (the default) and fully sorting non-factors.

